import 'dart:core';

class EndPoints {
  EndPoints._();
  static const startOnBoarding = "/mobile/auth/start-onboarding";
  static const onBoardingProgress = "/mobile/auth/onboarding-progress";
  static const getDefaultInterest = "/mobile/auth/default-interests";
  static const getDefaultTopics = "/mobile/auth/default-topics";
  static const getDefaultGoals = "/mobile/auth/default-goals";
  static const saveGoals = "/mobile/auth/save-goals";
  static const saveParentEmail = "/mobile/auth/save-parent-email";
  static const logIn = "/mobile/auth/login";
  static const logOut = "/mobile/auth/logout";
  static const saveTopics = "/mobile/auth/save-topics";
  static const saveInterest = "/mobile/auth/save-interests";
  static const saveReadings = "/mobile/auth/save-reading-goal";
  static const saveProfile = "/mobile/auth/save-profile-info";
  static const verifyEmail = "/mobile/auth/verify-email";
  static const createAccount = "/mobile/auth/create-account";
  static const saveAge = "/mobile/auth/save-age";
  static const socialLogin = "/mobile/auth/social-login";
  static const getStoryGoals = "/story-flow/goals";
  static const getStoryInterest = "/story-flow/interests";
  static const getStoryTopics = "/story-flow/topics";
  // static String getSearchTopics({required String query}) => "/api/v1/story-flow/topics?search=$query";
  static const getSearchTopics = "/story-flow/topics";
  static const getAllStories = "/story/mobile";
  static const forgotPassword = "/mobile/auth/forgot-password";
  static const resetPassword = "/mobile/auth/reset-password";
  static const createStoryIdea = "/story/ideas/generate-mobile";
  static const createStory = "/story/generate-from-idea";
  static const createStoryImage = "/story/generate-story-image";
  static const verifyForgotPassMail = "/mobile/auth/verify-recovery";
  static const verifyParentConsent = "/mobile/auth/parent-consent";
  static const refreshToken = "/mobile/auth/refresh-token";
  static const getHomeScreenTopics = "/story/topics?page=1&limit=10&createdBy=self";
  static String storeImage({required String storyId}) => "/story/mobile-story/$storyId/store-images";
  static String getStoryIdeasByTopicId({required String topicId}) => "/story/topics/$topicId/story-ideas?sortOrder=asc&sortOrder=asc";
  static String getStoryByStoryIdea({required String storyIdea}) => "/story/ideas/$storyIdea/story";
  static String browseAllTopics({required String storyIdea}) => "/story/topics?page=1&limit=20&createdBy=all";
}
