import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';
import 'package:redstreakapp/core/constants/app_color.dart';
import 'package:redstreakapp/core/constants/text_style.dart';
import 'package:redstreakapp/core/widgets/app_layout.dart';
import 'package:redstreakapp/core/widgets/app_text.dart';
import 'package:redstreakapp/core/routes/app_router.dart';
import 'package:redstreakapp/core/routes/user_routes.dart';
import 'package:redstreakapp/screens/dashboard.dart';
  import 'package:redstreakapp/models/home/browse_topic_model.dart';
import 'package:redstreakapp/models/home/topic_progress_model.dart';
import 'package:redstreakapp/providers/home/story_provider.dart';
import 'package:redstreakapp/screens/home/story/story_series_screen.dart';
import 'package:redstreakapp/screens/home/widgets/home_section_shimmers.dart';

class RandomTopicReadingScreen extends StatefulWidget {
  final Map<String, dynamic> progressResponse;
  final BrowseTopicModel? searchTopic;

  const RandomTopicReadingScreen({
    super.key,
    required this.progressResponse,
    this.searchTopic,
  });

  @override
  State<RandomTopicReadingScreen> createState() =>
      _RandomTopicReadingScreenState();
}

class _RandomTopicReadingScreenState extends State<RandomTopicReadingScreen> {
  TopicProgressModel? _progress;
  bool _initialized = false;
  bool _providerSet = false;
  bool _storyLoadTriggered = false;
  StoryProvider? _storyProviderForDispose;

  @override
  void initState() {
    super.initState();
    _parseProgress();
    if (widget.searchTopic != null) {
      final p = context.read<StoryProvider>();
      _storyProviderForDispose = p;
      p.setTopicFromSearch(widget.searchTopic);
    }
  }

  @override
  void dispose() {
    _storyProviderForDispose?.clearTopicFromSearch();
    super.dispose();
  }

  void _parseProgress() {
    try {
      final data = widget.progressResponse;
      if (data.isEmpty || data["data"] == null) {
        setState(() => _progress = null);
        return;
      }
      setState(() {
        _progress = TopicProgressModel.fromJson(
          Map<String, dynamic>.from(data as Map),
        );
        _initialized = true;
      });
    } catch (_) {
      setState(() => _progress = null);
    }
  }

  void _ensureProviderSet() {
    if (_progress == null || _providerSet || !mounted) return;
    _providerSet = true;
    context.read<StoryProvider>().setFromTopicProgress(_progress!);
  }

  void _showStoryNotGeneratedDialog(BuildContext context) {
    showDialog(
      context: context,

      barrierDismissible: false,

      builder: (dialogContext) {
        return AlertDialog(

          backgroundColor: AppColors.white,
          title: Text(
            "Story is not generated yet",
            style: AppTextStyles.textStyle20Regular.copyWith(
              color: AppColors.bluecolor,
            ),
          ),
          content: Text(
            "This story has not been generated by the author yet. You will be taken back to search.",
            style: AppTextStyles.sfProDisplayRegular(
              fontSize: 15.sp,
              color: AppColors.black.withValues(alpha: 0.8),
            ),
          ),
          actions: [
            TextButton(
              onPressed: () {
                Navigator.of(dialogContext).pop();
                if (!context.mounted) return;
                tabIndex.value = 1;
                AppRouter.indexedStackNavigationShell?.goBranch(1);
                AppRouter.goRouter.goNamed(AppRoutes.searchScreen.name);
              },
              child: Text(
                "OK",
                style: AppTextStyles.sfProDisplaySemibold(
                  fontSize: 17.sp,
                  color: AppColors.bluecolor,
                ),
              ),
            ),
          ],
        );
      },
    );
  }

  void _generateResumeStory() {
    final resume = _progress?.resume;
    if (resume == null || resume.storyIdeaId.isEmpty) {
      setState(() {});
      return;
    }

    final provider = context.read<StoryProvider>();
    final resumeIndex = provider.indexOfReadingByStoryIdeaId(resume.storyIdeaId);
    provider.fetchSingleStoryByIdea(
      storyIdeaId: resume.storyIdeaId,
      context: context,
      onSuccess: () => setState(() {}),
      insertAtIndex: resumeIndex >= 0 ? resumeIndex : null,
      showToast: false,
      onStoryNotGenerated: _showStoryNotGeneratedDialog,
    );
  }

  void _generateFirstStory() {
    final provider = context.read<StoryProvider>();
    final ideas = provider.storyIdea?.storyIdeas ?? [];
    if (ideas.isEmpty) return;

    provider.fetchSingleStoryByIdea(
      storyIdeaId: ideas.first.id,
      context: context,
      onSuccess: () => setState(() {}),
      showToast: false,
      onStoryNotGenerated: _showStoryNotGeneratedDialog,
    );
  }

  /// Auto-load resume story or first story once (no popup). After this, UI shows with Resume / Start over buttons.
  void _ensureStoryLoaded() {
    if (_progress == null || _storyLoadTriggered || !mounted) return;
    final provider = context.read<StoryProvider>();
    final ideas = provider.storyIdea?.storyIdeas ?? [];
    if (ideas.isEmpty) return;

    _storyLoadTriggered = true;
    setState(() {});

    if (_progress!.hasResume && _progress!.readings.isNotEmpty) {
      _generateResumeStory();
    } else {
      _generateFirstStory();
    }
  }

  Widget _buildErrorState() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          AppText(
            text: "Could not load topic progress.",
            style: AppTextStyles.sfProDisplayMedium(
              fontSize: 16.sp,
              color: AppColors.black.withValues(alpha: 0.7),
            ),
          ),
          16.w.verticalSpace,
          TextButton(
            onPressed: () {
              if (context.canPop()) {
                context.pop();
              } else {
                context.goNamed(AppRoutes.homeScreen.name);
                tabIndex.value = 0;
              }
            },
            child: const Text("Go back"),
          ),
        ],
      ),
    );
  }

  Widget _buildLoadingState() {
    return HomeSectionShimmer.generateStoryIdeasScreenShimmer();
  }

  Widget _buildBody(BuildContext context) {
    if (_progress == null && _initialized) {
      return _buildErrorState();
    }

    if (_progress == null) {
      return _buildLoadingState();
    }

    WidgetsBinding.instance.addPostFrameCallback((_) => _ensureProviderSet());
    WidgetsBinding.instance.addPostFrameCallback((_) => _ensureStoryLoaded());

    final provider = context.watch<StoryProvider>();
    final hasIdeas = provider.storyIdea?.storyIdeas.isNotEmpty ?? false;
    final hasStories = provider.stories.isNotEmpty;
    final isLoading = provider.isGenerateSingleStoryLoading;

    // Show loading until story is ready, then show screen with Resume / Start over buttons.
    if (hasIdeas && (!hasStories || isLoading)) {
      return _buildLoadingState();
    }

    // When resume is null and progress is 100%, show only normal Start (no Resume/Start over).
    final resumeNullAndComplete = _progress!.resume == null &&
        (_progress!.progress.percentComplete >= 100);
    return StoryReadingScreen(
      showAddToMyList: true,
      showResumeStartOverChoice: !resumeNullAndComplete,
      topicProgressPercent: _progress!.progress.percentComplete.clamp(0, 100),
    );
  }

  // void showLeaveStoryConfirmation({required BuildContext context}) {
  //   showDialog(
  //     context: context,
  //     builder: (dialogContext) {
  //       return AlertDialog(
  //         backgroundColor: AppColors.white,
  //         title: Text(
  //           "Are you sure you want to quit this story?",
  //           style: AppTextStyles.textStyle20Regular,
  //         ),
  //         actions: [
  //           TextButton(
  //             onPressed: () {
  //               dialogContext.pop();
  //               final provider = context.read<StoryProvider>();
  //               provider.clareStoryData();
  //               provider.clearStoryFields();
  //               provider.resetStoryPageIndex();
  //               provider.setCurrentStoryIndex = 0;
  //               tabIndex.value = 1;
  //               AppRouter.indexedStackNavigationShell?.goBranch(1);
  //               AppRouter.goRouter.goNamed(AppRoutes.searchScreen.name);
  //             },
  //             child: Text(
  //               "Quit",
  //               style: AppTextStyles.sfProDisplayRegular(
  //                 color: AppColors.redColor,
  //                 fontSize: 17.sp,
  //               ),
  //             ),
  //           ),
  //           TextButton(
  //             onPressed: () {
  //               Navigator.of(dialogContext).pop();
  //             },
  //             child: Text(
  //               "Cancel",
  //               style: AppTextStyles.sfProDisplayRegular(
  //                 color: AppColors.black,
  //                 fontSize: 17.sp,
  //               ),
  //             ),
  //           ),
  //         ],
  //       );
  //     },
  //   );
  // }

  @override
  Widget build(BuildContext context) {
    return AppLayout(
        body: SafeArea(
          child: _buildBody(context),
        ),
      );
    
    // PopScope(
    //   canPop: false,
    //   onPopInvokedWithResult: (didPop, result) {
    //     if (didPop) return;
    //     showLeaveStoryConfirmation(context: context);
    //   },
    //   child: 
    // );
  }
}
