enum AppRoutes {
  splashScreen,
  loginScreen,
  signUpScreen,
  enterAgeScreen,

  /////Below 16////
  parentEmailScreen,
  consentStatusScreen,

  /////Above 16////
  createAccountScreen,

  /////Onboarding////
  profileInfoScreen,
  readingGoalScreen,
  interestsScreen,
  topicsScreen,
  goalsScreen,

  successScreen,
  subscriptionScreen,

  dashBoardScreen,
  bookReadingScreen,
  readingScreen,
  enterQuizNumbersScreen,
  startQuizScreen,
  quizQuestionScreen,
  quizCompletedScreen,
  episodeCompletedScreen,
  whatInterestScreen,
  forgotPasswordScreen,
  verifyOtpScreen,
  resetPasswordScreen,
  storyGoalsScreen,
  storyInterestScreen,
  storyTopicsScreen,
  homeScreen,
  customTopicScreen,
  storyReadingGoalScreen,
  verifyParentConsentScreen,
  createdStorySummaryScreen,
  createdStoryReadingScreen,
  storyIdeasScreen,
  storyReadingScreen,
  sharedStoryScreen,
  searchScreen,
  randomStorySeriesScreen,
  practiceZoneScreen,
  notificationScreen,
  createdIdeasListScreen,
  profileScreen,
  settingsScreen,
  preferencesScreen,
  settingsNotificationScreen,
  editProfileScreen,
  verifyProfileContactScreen,
  remindersSettingsScreen,
  friendsNotificationSettingsScreen,
  groupsNotificationSettingsScreen,
  yourBooksScreen,
  createGroupScreen,
  addMembersScreen,
  joinGroupScreen,
  groupListScreen,
  viewGroupScreen,
  groupDetailsScreen,
  streakRankingScreen,
  curiosityReadingScreen,
  findYourBooksScreen,
  bookDetailsScreen,
  shareStoriesInGroupScreen,
  friendsListScreen,
  userProfileGroupsListScreen,
  userProfileTopicsListScreen,
  familyMembersListScreen,
  addFamilyMemberScreen,
  friendDetailsScreen,
  addFriendsScreen,
  editInterestsScreen,
  mySavedSeriesScreen,
  exploreScreen,
  achivementsScreen,
}
