enum AppRoutes {
  splashScreen,
  loginScreen,
  signUpScreen,
  enterAgeScreen,

  /////Below 16////
  parentEmailScreen,
  consentStatusScreen,

  /////Above 16////
  createAccountScreen,

  /////Onboarding////
  profileInfoScreen,
  readingGoalScreen,
  interestsScreen,
  topicsScreen,
  goalsScreen,

  successScreen,
  subscriptionScreen,

  dashBoardScreen,
  bookReadingScreen,
  readingScreen,
  enterQuizNumbersScreen,
  startQuizScreen,
  quizQuestionScreen,
  quizCompletedScreen,
  whatInterestScreen,
  forgotPasswordScreen,
  verifyOtpScreen,
  resetPasswordScreen,
  storyGoalsScreen,
  storyInterestScreen,
  storyTopicsScreen,
  homeScreen,
  customTopicScreen,
  storyReadingGoalScreen,
  verifyParentConsentScreen,
  createdStorySummaryScreen,
  createdStoryReadingScreen,
  storyIdeasScreen,
  storyReadingScreen,
  sharedStoryScreen,
  searchScreen,
  randomStorySeriesScreen,
  practiceZoneScreen,
  notificationScreen,
  createdIdeasListScreen,
  profileScreen,
  settingsScreen,
  preferencesScreen,
  settingsNotificationScreen,
  editProfileScreen,
  remindersSettingsScreen,
  friendsNotificationSettingsScreen,
  groupsNotificationSettingsScreen,
  yourEBooksScreen,
}
