import 'package:flutter_dotenv/flutter_dotenv.dart';

class AppConstants {
  AppConstants._();

  static String get serverClientId => dotenv.env['SERVER_CLIENT_ID']!;
  // ??"1072520967140-7566tlns04ge757cqiailkl8j405a9am.apps.googleusercontent.com";
  static String get clientIdIos => dotenv.env['CLIENT_ID_IOS']!;
  static String get imageBaseUrl => dotenv.env['IMAGE_BASE_URL'] ?? 'https://whyse.com';
  // ??
  // "1072520967140-6hu941fhtps4i2sjkl1gf31l395j2ia2.apps.googleusercontent.com";
  //*===============================
  // static const String serverClientId =
  //     "1072520967140-7566tlns04ge757cqiailkl8j405a9am.apps.googleusercontent.com";
  // static const String clientIdIos =
  //     "1072520967140-6hu941fhtps4i2sjkl1gf31l395j2ia2.apps.googleusercontent.com";
  static const String domain = "whyse.com",
      parentConsentPath = "/verify-parent-consent",
      forgotPasswordPath = "/verify-reset-password",
      storyPath = "/story",
      storyIdeaIdParam = "id",
      topicIdParam = "topicId",
      age = "AGE",
      email = "EMAIL",
      parentEmail = "PARENT_EMAIL",
      consentStatus = "CONSENT_STATUS",
      createAccount = "CREATE_ACCOUNT",
      profileInfo = "PROFILE_INFO",
      readingGoal = "READING_GOAL",
      interest = "INTERESTS",
      topics = "TOPICS",
      goals = "GOALS",
      completed = "COMPLETED",
      accepted = "ACCEPTED",
      unAuthorized = "unauthorized",
      trueSt = "true",
      alreadyVerified = "alreadyVerified",
      accessToken = "access_token",
      token = "token",
      type = "type",
      signup = "signup",
      recovery = "recovery",
      falseSt = "false";


      static const List<String> preferredLanguages = ["English", "Hindi", "Arabic", "French"];

  static const List<String> countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "UK",
    "USA",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
  ];
}
